Create cli/`Scan.java`
atsign-foundation/at_java pull request #19
Opened 2022-06-24 13:07 UTC by JeremyTubongbanua

**- What I did**
- Created a Scan CLI demo where user puts `atSign` as the one and only argument.
- Program will fetch secondary address, initialize connection, pkam auth, then run a raw `scan` command.

**- How I did it**
Just execute the `scan` command after pkam auth.

**- How to verify it**
```
cmd /C ""C:\Program Files\OpenJDK\openjdk-11.0.13_8\bin\java.exe" @C:\Users\madiv\AppData\Local\Temp\cp_b3yf38okkfdcxflryrhfm2zes.argfile org.atsign.client.cli.Scan @sportsunconscious"
RootURL from config: root.atsign.wtf:64
Starting PKAM
Retrieved Secondary URL of @sportsunconscious: ddbe1816-f40f-5b9f-bb2a-ba1492b93aec.staging0001.atsign.zone:3198
Initialized connection: ddbe1816-f40f-5b9f-bb2a-ba1492b93aec.staging0001.atsign.zone:3198
Successfully retrieved .atKeys.
PKAM Auth Success
data:["@farinataanxious:lemon@sportsunconscious","@farinataanxious:shared_key@sportsunconscious","@farinataanxious:test@sportsunconscious","@sportsunconscious:signing_privatekey@sportsunconscious","cached:public:publickey@farinataanxious","public:publickey@sportsunconscious","public:signing_publickey@sportsunconscious","shared_key.farinataanxious@sportsunconscious"]
```
**- Description for the changelog**

2022-06-24 14:01 UTC, gkc requested changes
V good first draft. What I would expect though is that the scan be implemented in AtClient's `    CompletableFuture<List<AtKey>> getAtKeys(String regex);` method, and then that the Scan CLI follow the pattern of the other CLIs in creating an AtClient via one of the factory methods, and then calling its `getAtKeys` method

2022-06-25 22:14 UTC, JeremyTubongbanua commented
@gkc 

I've implemented a lot to `_getAtKeys` in `AtClientImpl`.

The terminal copy pasta below is from running CLI `Scan.java`. 
Please let me know if I'm interpreting any of the keys wrong and if I'm missing anything.

Next steps is to find out how to obtain other metadata from keys like `ttl`. Is this data like `ttb` and `ttl` encrypted in the AtValue?

```
C:\Users\madiv\Desktop\GitHub\at_java> cmd /C ""C:\Program Files\OpenJDK\openjdk-11.0.13_8\bin\java.exe" @C:\Users\madiv\AppData\Local\Temp\cp_b3yf38okkfdcxflryrhfm2zes.argfile org.atsign.client.cli.Scan root.atsign.wtf:64 @sportsunconscious false"
Found address of atSign "@sportsunconscious": ddbe1816-f40f-5b9f-bb2a-ba1492b93aec.staging0001.atsign.zone:3198
atKeys: [
        @farinataanxious:lemon@sportsunconscious
        @farinataanxious:shared_key@sportsunconscious
        @farinataanxious:test@sportsunconscious
        @sportsunconscious:shared_key@sportsunconscious
        @sportsunconscious:signing_privatekey@sportsunconscious
        public:publickey@farinataanxious
        public:publickey@sportsunconscious
        public:signing_publickey@sportsunconscious
        shared_key.farinataanxious.farinataanxious@sportsunconscious    
        shared_key.sportsunconscious.sportsunconscious@sportsunconscious
]
======================
@farinataanxious:lemon@sportsunconscious
KeyName: lemon
Namespace: null
SharedBy: @sportsunconscious
SharedWith: @farinataanxious
KeyType: class org.atsign.common.Keys$SharedKey
isCached: false
======================

======================
@farinataanxious:shared_key@sportsunconscious
KeyName: shared_key
Namespace: null
SharedBy: @sportsunconscious
SharedWith: @farinataanxious
KeyType: class org.atsign.common.Keys$SharedKey
isCached: false
======================

======================
@farinataanxious:test@sportsunconscious
KeyName: test
Namespace: null
SharedBy: @sportsunconscious
SharedWith: @farinataanxious
KeyType: class org.atsign.common.Keys$SharedKey
isCached: false
======================

======================
@sportsunconscious:shared_key@sportsunconscious
KeyName: shared_key
Namespace: null
SharedBy: @sportsunconscious
SharedWith: @sportsunconscious
KeyType: class org.atsign.common.Keys$SharedKey
isCached: false
======================

======================
@sportsunconscious:signing_privatekey@sportsunconscious
KeyName: signing_privatekey
Namespace: null
SharedBy: @sportsunconscious
SharedWith: @sportsunconscious
KeyType: class org.atsign.common.Keys$SharedKey
isCached: false
======================

======================
public:publickey@farinataanxious
KeyName: publickey
Namespace: null
SharedBy: @farinataanxious
SharedWith: null
KeyType: class org.atsign.common.Keys$PublicKey
isCached: true
======================

======================
public:publickey@sportsunconscious
KeyName: publickey
Namespace: null
SharedBy: @sportsunconscious
SharedWith: null
KeyType: class org.atsign.common.Keys$PublicKey
isCached: false
======================

======================
public:signing_publickey@sportsunconscious
KeyName: signing_publickey
Namespace: null
SharedBy: @sportsunconscious
SharedWith: null
KeyType: class org.atsign.common.Keys$PublicKey
isCached: false
======================

======================
shared_key.farinataanxious.farinataanxious@sportsunconscious
KeyName: shared_key.farinataanxious
Namespace: farinataanxious
SharedBy: @sportsunconscious
SharedWith: null
KeyType: class org.atsign.common.Keys$SelfKey
isCached: false
======================

======================
shared_key.sportsunconscious.sportsunconscious@sportsunconscious
KeyName: shared_key.sportsunconscious
Namespace: sportsunconscious
SharedBy: @sportsunconscious
SharedWith: null
KeyType: class org.atsign.common.Keys$SelfKey
isCached: false
======================
```

2022-06-26 22:29 UTC, JeremyTubongbanua commented
Another test but with an at sign with more keys
```
C:\Users\madiv\Desktop\GitHub\at_java> cmd /C ""C:\Program Files\OpenJDK\openjdk-11.0.13_8\bin\java.exe" @C:\Users\madiv\AppData\Local\Temp\cp_b3yf38okkfdcxflryrhfm2zes.argfile org.atsign.client.cli.Scan root.atsign.org:64 @smoothalligator false"
Found address of atSign "@smoothalligator": 245b44d4-a4bd-5f33-b077-c559f956486a.swarm0001.atsign.zone:1722
atKeys: [
        @abbcservicesinc:shared_key@smoothalligator
        @denise:shared_key@smoothalligator
        @fascinatingsnow:shared_key@smoothalligator
        @hacktheleague:shared_key@smoothalligator
        @smoothalligator:signing_privatekey@smoothalligator
        @wildgreen:shared_key@smoothalligator
        _latestnotificationid.fourballcorporate9.fourballcorporate9@smoothalligator
        _latestnotificationid.mospherepro.mospherepro@smoothalligator
        atconnections.abbcservicesinc.smoothalligator.at_contact.mospherepro.abbcservicesinc@smoothalligator
        atconnections.denise.smoothalligator.at_contact.mospherepro.denise@smoothalligator
        atconnections.hacktheleague.smoothalligator.at_contact.mospherepro.hacktheleague@smoothalligator
        atconnections.wildgreen.smoothalligator.at_contact.mospherepro.wildgreen@smoothalligator
        @smoothalligator:shared_key@abbcservicesinc
        @smoothalligator:shared_key@denise
        @smoothalligator:shared_key@fascinatingsnow
        @smoothalligator:shared_key@wildgreen
        public:firstname.wavi.wavi@abbcservicesinc
        public:firstname.wavi.wavi@wildgreen
        public:image.wavi.wavi@abbcservicesinc
        public:image.wavi.wavi@denise
        public:image.wavi.wavi@wildgreen
        public:lastname.wavi.wavi@abbcservicesinc
        public:lastname.wavi.wavi@wildgreen
        public:publickey@abbcservicesinc
        public:publickey@denise
        public:publickey@fascinatingsnow
        public:publickey@hacktheleague
        public:publickey@wildgreen
        public:privateaccount.wavi.wavi@smoothalligator
        public:publickey@smoothalligator
        public:signing_publickey@smoothalligator
        publickey.fascinatingsnow.fascinatingsnow@smoothalligator
        senthistory_v2.mospherepro.mospherepro@smoothalligator
        shared_key.abbcservicesinc.abbcservicesinc@smoothalligator
        shared_key.denise.denise@smoothalligator
        shared_key.fascinatingsnow.fascinatingsnow@smoothalligator
        shared_key.hacktheleague.hacktheleague@smoothalligator
        shared_key.wildgreen.wildgreen@smoothalligator
]
======================
Full KeyName: @abbcservicesinc:shared_key@smoothalligator
KeyName: shared_key
Namespace: null
SharedBy: @smoothalligator
SharedWith: @abbcservicesinc
KeyType: class org.atsign.common.Keys$SharedKey
isCached: false
======================

======================
Full KeyName: @denise:shared_key@smoothalligator
KeyName: shared_key
Namespace: null
SharedBy: @smoothalligator
SharedWith: @denise
KeyType: class org.atsign.common.Keys$SharedKey
isCached: false
======================

======================
Full KeyName: @fascinatingsnow:shared_key@smoothalligator
KeyName: shared_key
Namespace: null
SharedBy: @smoothalligator
SharedWith: @fascinatingsnow
KeyType: class org.atsign.common.Keys$SharedKey
isCached: false
======================

======================
Full KeyName: @hacktheleague:shared_key@smoothalligator
KeyName: shared_key
Namespace: null
SharedBy: @smoothalligator
SharedWith: @hacktheleague
KeyType: class org.atsign.common.Keys$SharedKey
isCached: false
======================

======================
Full KeyName: @smoothalligator:signing_privatekey@smoothalligator
KeyName: signing_privatekey
Namespace: null
SharedBy: @smoothalligator
SharedWith: @smoothalligator
KeyType: class org.atsign.common.Keys$SharedKey
isCached: false
======================

======================
Full KeyName: @wildgreen:shared_key@smoothalligator
KeyName: shared_key
Namespace: null
SharedBy: @smoothalligator
SharedWith: @wildgreen
KeyType: class org.atsign.common.Keys$SharedKey
isCached: false
======================

======================
Full KeyName: _latestnotificationid.fourballcorporate9.fourballcorporate9@smoothalligator
KeyName: _latestnotificationid.fourballcorporate9
Namespace: fourballcorporate9
SharedBy: @smoothalligator
SharedWith: null
KeyType: class org.atsign.common.Keys$PrivateHiddenKey
isCached: false
======================

======================
Full KeyName: _latestnotificationid.mospherepro.mospherepro@smoothalligator
KeyName: _latestnotificationid.mospherepro
Namespace: mospherepro
SharedBy: @smoothalligator
SharedWith: null
KeyType: class org.atsign.common.Keys$PrivateHiddenKey
isCached: false
======================

======================
Full KeyName: atconnections.abbcservicesinc.smoothalligator.at_contact.mospherepro.abbcservicesinc@smoothalligator
KeyName: atconnections.abbcservicesinc.smoothalligator.at_contact.mospherepro
Namespace: abbcservicesinc
SharedBy: @smoothalligator
SharedWith: null
KeyType: class org.atsign.common.Keys$SelfKey
isCached: false
======================

======================
Full KeyName: atconnections.denise.smoothalligator.at_contact.mospherepro.denise@smoothalligator
KeyName: atconnections.denise.smoothalligator.at_contact.mospherepro
Namespace: denise
SharedBy: @smoothalligator
SharedWith: null
KeyType: class org.atsign.common.Keys$SelfKey
isCached: false
======================

======================
Full KeyName: atconnections.hacktheleague.smoothalligator.at_contact.mospherepro.hacktheleague@smoothalligator
KeyName: atconnections.hacktheleague.smoothalligator.at_contact.mospherepro
Namespace: hacktheleague
SharedBy: @smoothalligator
SharedWith: null
KeyType: class org.atsign.common.Keys$SelfKey
isCached: false
======================

======================
Full KeyName: atconnections.wildgreen.smoothalligator.at_contact.mospherepro.wildgreen@smoothalligator
KeyName: atconnections.wildgreen.smoothalligator.at_contact.mospherepro
Namespace: wildgreen
SharedBy: @smoothalligator
SharedWith: null
KeyType: class org.atsign.common.Keys$SelfKey
isCached: false
======================

======================
Full KeyName: @smoothalligator:shared_key@abbcservicesinc
KeyName: shared_key
Namespace: null
SharedBy: @abbcservicesinc
SharedWith: @smoothalligator
KeyType: class org.atsign.common.Keys$SharedKey
isCached: true
======================

======================
Full KeyName: @smoothalligator:shared_key@denise
KeyName: shared_key
Namespace: null
SharedBy: @denise
SharedWith: @smoothalligator
KeyType: class org.atsign.common.Keys$SharedKey
isCached: true
======================

======================
Full KeyName: @smoothalligator:shared_key@fascinatingsnow
KeyName: shared_key
Namespace: null
SharedBy: @fascinatingsnow
SharedWith: @smoothalligator
KeyType: class org.atsign.common.Keys$SharedKey
isCached: true
======================

======================
Full KeyName: @smoothalligator:shared_key@wildgreen
KeyName: shared_key
Namespace: null
SharedBy: @wildgreen
SharedWith: @smoothalligator
KeyType: class org.atsign.common.Keys$SharedKey
isCached: true
======================

======================
Full KeyName: public:firstname.wavi.wavi@abbcservicesinc
KeyName: firstname.wavi
Namespace: wavi
SharedBy: @abbcservicesinc
SharedWith: null
KeyType: class org.atsign.common.Keys$PublicKey
isCached: true
======================

======================
Full KeyName: public:firstname.wavi.wavi@wildgreen
KeyName: firstname.wavi
Namespace: wavi
SharedBy: @wildgreen
SharedWith: null
KeyType: class org.atsign.common.Keys$PublicKey
isCached: true
======================

======================
Full KeyName: public:image.wavi.wavi@abbcservicesinc
KeyName: image.wavi
Namespace: wavi
SharedBy: @abbcservicesinc
SharedWith: null
KeyType: class org.atsign.common.Keys$PublicKey
isCached: true
======================

======================
Full KeyName: public:image.wavi.wavi@denise
KeyName: image.wavi
Namespace:  [...]

2022-06-26 23:00 UTC, JeremyTubongbanua commented
Another test with my atSign's key
```
C:\Users\madiv\Desktop\GitHub\at_java> cmd /C ""C:\Program Files\OpenJDK\openjdk-11.0.13_8\bin\java.exe" @C:\Users\madiv\AppData\Local\Temp\cp_b3yf38okkfdcxflryrhfm2zes.argfile org.atsign.client.cli.Scan root.atsign.org:64 @smoothalligator false"
Found address of atSign "@smoothalligator": 245b44d4-a4bd-5f33-b077-c559f956486a.swarm0001.atsign.zone:1722
atKeys: [
        @abbcservicesinc:shared_key@smoothalligator
        @denise:shared_key@smoothalligator
        @fascinatingsnow:shared_key@smoothalligator
        @hacktheleague:shared_key@smoothalligator
        @smoothalligator:signing_privatekey@smoothalligator
        @wildgreen:shared_key@smoothalligator
        _latestnotificationid.fourballcorporate9.fourballcorporate9@smoothalligator
        _latestnotificationid.mospherepro.mospherepro@smoothalligator
        atconnections.abbcservicesinc.smoothalligator.at_contact.mospherepro.abbcservicesinc@smoothalligator
        atconnections.denise.smoothalligator.at_contact.mospherepro.denise@smoothalligator
        atconnections.hacktheleague.smoothalligator.at_contact.mospherepro.hacktheleague@smoothalligator
        atconnections.wildgreen.smoothalligator.at_contact.mospherepro.wildgreen@smoothalligator
        @smoothalligator:shared_key@abbcservicesinc
        @smoothalligator:shared_key@denise
        @smoothalligator:shared_key@fascinatingsnow
        @smoothalligator:shared_key@wildgreen
        public:firstname.wavi.wavi@abbcservicesinc
        public:firstname.wavi.wavi@wildgreen
        public:image.wavi.wavi@abbcservicesinc
        public:image.wavi.wavi@denise
        public:image.wavi.wavi@wildgreen
        public:lastname.wavi.wavi@abbcservicesinc
        public:lastname.wavi.wavi@wildgreen
        public:publickey@abbcservicesinc
        public:publickey@denise
        public:publickey@fascinatingsnow
        public:publickey@hacktheleague
        public:publickey@wildgreen
        public:privateaccount.wavi.wavi@smoothalligator
        public:publickey@smoothalligator
        public:signing_publickey@smoothalligator
        publickey.fascinatingsnow.fascinatingsnow@smoothalligator
        senthistory_v2.mospherepro.mospherepro@smoothalligator
        shared_key.abbcservicesinc.abbcservicesinc@smoothalligator
        shared_key.denise.denise@smoothalligator
        shared_key.fascinatingsnow.fascinatingsnow@smoothalligator
        shared_key.hacktheleague.hacktheleague@smoothalligator
        shared_key.wildgreen.wildgreen@smoothalligator
]
======================
Full KeyName: @abbcservicesinc:shared_key@smoothalligator
KeyName: shared_key
Namespace: null
SharedBy: @smoothalligator
SharedWith: @abbcservicesinc
KeyType: SharedKey
isCached: false
======================

======================
Full KeyName: @denise:shared_key@smoothalligator
KeyName: shared_key
Namespace: null
SharedBy: @smoothalligator
SharedWith: @denise
KeyType: SharedKey
isCached: false
======================

======================
Full KeyName: @fascinatingsnow:shared_key@smoothalligator
KeyName: shared_key
Namespace: null
SharedBy: @smoothalligator
SharedWith: @fascinatingsnow
KeyType: SharedKey
isCached: false
======================

======================
Full KeyName: @hacktheleague:shared_key@smoothalligator
KeyName: shared_key
Namespace: null
SharedBy: @smoothalligator
SharedWith: @hacktheleague
KeyType: SharedKey
isCached: false
======================

======================
Full KeyName: @smoothalligator:signing_privatekey@smoothalligator
KeyName: signing_privatekey
Namespace: null
SharedBy: @smoothalligator
SharedWith: @smoothalligator
KeyType: SelfKey
isCached: false
======================

======================
Full KeyName: @wildgreen:shared_key@smoothalligator
KeyName: shared_key
Namespace: null
SharedBy: @smoothalligator
SharedWith: @wildgreen
KeyType: SharedKey
isCached: false
======================

======================
Full KeyName: _latestnotificationid.fourballcorporate9.fourballcorporate9@smoothalligator
KeyName: _latestnotificationid.fourballcorporate9
Namespace: fourballcorporate9
SharedBy: @smoothalligator
SharedWith: null
KeyType: PrivateHiddenKey
isCached: false
======================

======================
Full KeyName: _latestnotificationid.mospherepro.mospherepro@smoothalligator
KeyName: _latestnotificationid.mospherepro
Namespace: mospherepro
SharedBy: @smoothalligator
SharedWith: null
KeyType: PrivateHiddenKey
isCached: false
======================

======================
Full KeyName: atconnections.abbcservicesinc.smoothalligator.at_contact.mospherepro.abbcservicesinc@smoothalligator
KeyName: atconnections.abbcservicesinc.smoothalligator.at_contact.mospherepro
Namespace: abbcservicesinc
SharedBy: @smoothalligator
SharedWith: null
KeyType: SelfKey
isCached: false
======================

======================
Full KeyName: atconnections.denise.smoothalligator.at_contact.mospherepro.denise@smoothalligator
KeyName: atconnections.denise.smoothalligator.at_contact.mospherepro
Namespace: denise
SharedBy: @smoothalligator
SharedWith: null
KeyType: SelfKey
isCached: false
======================

======================
Full KeyName: atconnections.hacktheleague.smoothalligator.at_contact.mospherepro.hacktheleague@smoothalligator
KeyName: atconnections.hacktheleague.smoothalligator.at_contact.mospherepro
Namespace: hacktheleague
SharedBy: @smoothalligator
SharedWith: null
KeyType: SelfKey
isCached: false
======================

======================
Full KeyName: atconnections.wildgreen.smoothalligator.at_contact.mospherepro.wildgreen@smoothalligator
KeyName: atconnections.wildgreen.smoothalligator.at_contact.mospherepro
Namespace: wildgreen
SharedBy: @smoothalligator
SharedWith: null
KeyType: SelfKey
isCached: false
======================

======================
Full KeyName: @smoothalligator:shared_key@abbcservicesinc
KeyName: shared_key
Namespace: null
SharedBy: @abbcservicesinc
SharedWith: @smoothalligator
KeyType: SharedKey
isCached: true
======================

======================
Full KeyName: @smoothalligator:shared_key@denise
KeyName: shared_key
Namespace: null
SharedBy: @denise
SharedWith: @smoothalligator
KeyType: SharedKey
isCached: true
======================

======================
Full KeyName: @smoothalligator:shared_key@fascinatingsnow
KeyName: shared_key
Namespace: null
SharedBy: @fascinatingsnow
SharedWith: @smoothalligator
KeyType: SharedKey
isCached: true
======================

======================
Full KeyName: @smoothalligator:shared_key@wildgreen
KeyName: shared_key
Namespace: null
SharedBy: @wildgreen
SharedWith: @smoothalligator
KeyType: SharedKey
isCached: true
======================

======================
Full KeyName: public:firstname.wavi.wavi@abbcservicesinc
KeyName: firstname.wavi
Namespace: wavi
SharedBy: @abbcservicesinc
SharedWith: null
KeyType: PublicKey
isCached: true
======================

======================
Full KeyName: public:firstname.wavi.wavi@wildgreen
KeyName: firstname.wavi
Namespace: wavi
SharedBy: @wildgreen
SharedWith: null
KeyType: PublicKey
isCached: true
======================

======================
Full KeyName: public:image.wavi.wavi@abbcservicesinc
KeyName: image.wavi
Namespace: wavi
SharedBy: @abbcservicesinc
SharedWith: null
KeyType: PublicKey
isCached: true
======================

======================
Full KeyName: public:image.wavi.wavi@denise
KeyName: image.wavi
Namespace: wavi
SharedBy: @denise
SharedWith: null
KeyType: PublicKey
isCached: true
======================

======================
Full KeyName: public:image.wavi.wavi@wildgreen
KeyName: image.wavi
Namespace: wavi
SharedBy: @wildgreen
SharedWith: null
KeyType: PublicKey
isCached: true
======================

======================
Full KeyName: public:lastname.wavi.wavi@abbcservicesinc
KeyName: lastname.wavi
Namespace: wavi
SharedBy: @abbcservicesinc
SharedWith: null
KeyType: PublicKey
isCached: true
======================

======================
Full KeyName: public:las [...]

2022-06-26 23:05 UTC, JeremyTubongbanua commented
Some important ones to have a look at:

1. `@smoothalligator:signing_privatekey@smoothalligator` - follows SharedKey format but should be a SelfKey object. Is this right?
```
======================
Full KeyName: @smoothalligator:signing_privatekey@smoothalligator
KeyName: signing_privatekey
Namespace: null
SharedBy: @smoothalligator
SharedWith: @smoothalligator
KeyType: SelfKey
isCached: false
======================
```


2. PrivateHiddenKey - if this is an internal key, how come I am able to see it with `scan` ?
```
======================
Full KeyName: _latestnotificationid.fourballcorporate9.fourballcorporate9@smoothalligator
KeyName: _latestnotificationid.fourballcorporate9
Namespace: fourballcorporate9
SharedBy: @smoothalligator
SharedWith: null
KeyType: PrivateHiddenKey
isCached: false
======================
```

3. Namespace `abbcservicesinc`. How do I know that this is the namespace and not part of the keyName?
```
======================
Full KeyName: atconnections.abbcservicesinc.smoothalligator.at_contact.mospherepro.abbcservicesinc@smoothalligator
KeyName: atconnections.abbcservicesinc.smoothalligator.at_contact.mospherepro
Namespace: abbcservicesinc
SharedBy: @smoothalligator
SharedWith: null
KeyType: SelfKey
isCached: false
======================
```
How am I supposed to know if it is

**Scenario 1**
`keyName`==`atconnections.abbcservicesinc.smoothalligator.at_contact.mospherepro.abbcservicesinc`
`namespace`==`null`

**Scenario 2**
`keyName`==`atconnections.abbcservicesinc.smoothalligator.at_contact.mospherepro`
`namespace`==`abbcservicesinc`

What I am noticing is that every SelfKey has a namespace,, so would namespace==`null` never be possible with a SelfKey? 

4. These are SelfKeys although they have `shared_key` in the keyName, right?
```
======================
Full KeyName: shared_key.wildgreen.wildgreen@smoothalligator
KeyName: shared_key.wildgreen
Namespace: wildgreen
SharedBy: @smoothalligator
SharedWith: null
KeyType: SelfKey
isCached: false
======================
```

2022-06-30 12:28 UTC, gkc commented
> 1. `@smoothalligator:signing_privatekey@smoothalligator` - follows SharedKey format but should be a SelfKey object. Is this right?

Yes because @smoothalligator is both sharedBy and sharedWith

> 2. PrivateHiddenKey - if this is an internal key, how come I am able to see it with `scan` ?

Complicated answer. What `scan` actually returns is most clearly understood by looking at the server's [ScanVerbHandler](https://github.com/atsign-foundation/at_server/blob/trunk/at_secondary/at_secondary_server/lib/src/verb/handler/scan_verb_handler.dart#L129)

Note there was [a recent PR](https://github.com/atsign-foundation/at_server/pull/782) which added a new parameter 'showHiddenKeys' to enable an authenticated scan to return some keys which previously were not returned


> 3. Namespace `abbcservicesinc`. How do I know that this is the namespace and not part of the keyName?

You don't. You can't.

> 
> ```
> ======================
> Full KeyName: atconnections.abbcservicesinc.smoothalligator.at_contact.mospherepro.abbcservicesinc@smoothalligator
> KeyName: atconnections.abbcservicesinc.smoothalligator.at_contact.mospherepro
> Namespace: abbcservicesinc
> SharedBy: @smoothalligator
> SharedWith: null
> KeyType: SelfKey
> isCached: false
> ======================
> ```
> 
> How am I supposed to know if it is
> 
> **Scenario 1** `keyName`==`atconnections.abbcservicesinc.smoothalligator.at_contact.mospherepro.abbcservicesinc` `namespace`==`null`
> 
> **Scenario 2** `keyName`==`atconnections.abbcservicesinc.smoothalligator.at_contact.mospherepro` `namespace`==`abbcservicesinc`

I don't think you can. It *might* be OK to infer that the namespace is `abbcservicesinc` IFF your client / preferences / something else allows you to determine that you have a namespace called `abbcservicesinc`

For example, the 'namespace' might originally have been `abbcservicesinc.smoothalligator.at_contact.mospherepro.abbcservicesinc` with the 'keyName' being 'atconnections'

🤷‍♀️


> 
> What I am noticing is that every SelfKey has a namespace,, so would namespace==`null` never be possible with a SelfKey?

That might empirically be true but I don't think is a guarantee


> 4. These are SelfKeys although they have `shared_key` in the keyName, right?
> Full KeyName: shared_key.wildgreen@smoothalligator

Yes. shared_key is a special thing. See also my comment in your doc [here](https://docs.google.com/document/d/1E-FIHySO73k036kaXnkuUESkOQ2PUOLex2t7fMovc4I/edit?disco=AAAAbptTxsA) 

See also Java SDK AtClientImpl.java the `private String _put(SharedKey sharedKey, String value)` method for most concise code blocks which explain what's going with 'shared_key'

2022-06-30 12:45 UTC, gkc requested changes

2022-06-30 12:45 UTC, gkc commented on at_client/src/main/java/org/atsign/client/api/impl/clients/AtClientImpl.java
> +        String[] rawArray = StringUtil.getRawStringArrayFromScanRawResponseString(rawResponse.data);
As per discussion just now, please decode using the Jackson ObjectMapper something like 
```
ObjectMapper mapper = new ObjectMapper();
try {
    List<String> strings = mapper.readerForListOf(String.class).readValue(value.data);
}
``` etc

2022-06-30 12:45 UTC, gkc commented on at_client/src/main/java/org/atsign/client/api/impl/clients/AtClientImpl.java
> +        }
As discussed just now: most of what's within the for loop should be made available via a static `fromString()` method in Keys.java, on the Keys class. That way, this same functionality which is hugely useful, will be available from everywhere not just here in AtClientImpl

I've proposed adding the static fromString() to the Keys class rather than the Keys.AtKey class so that later on we have the option of adding static fromString() methods to all of the concrete subclasses of AtKey (we currently have one on SharedKey)

2022-06-30 12:45 UTC, gkc commented on at_client/src/main/java/org/atsign/client/util/KeyStringUtil.java
> +}
It's probably OK to leave this code here in KeyStringUtil as is. Main thing to move is the stuff that is currently inside the for loop in your _getAtKeys() method

2022-07-04 13:43 UTC, JeremyTubongbanua commented
Made a fix in 51ed6b0fabe9037f3c331d01a4aee4cb72e098c8

![image](https://user-images.githubusercontent.com/79019866/177167054-7b628898-0a30-4a58-8241-eb6353933037.png)

SelfKey that are `shared_key`s will now have a namespace of `null` and a keyName of `shared_key.denise`
(Before, it would make `denise` the namespace).

2022-07-04 18:43 UTC, JeremyTubongbanua commented
## As of commit 7865f72a0ab1f346185530901e13aed70b9b4df5 , 

### 1. AtClient.getAtKeys(String)

There are 3 important parts in `getAtKeys(String)` 
```java
private List<AtKey> _getAtKeys(String regex) throws AtException {
    Secondary.Response scanRawResponse = executeCommand("scan " + regex, false);
    // 1
    String[] rawArray = StringUtil.getRawStringArrayFromScanRawResponseString(scanRawResponse.data); // eg {"public:some_key1@bob", "@alice:some_key2.namespace@bob"}
    List<AtKey> atKeys = new ArrayList<AtKey>(); 
    for(String atKeyRaw : rawArray) { // eg atKeyRaw == @bob:phone@alice
        // 2
        AtKey atKey = Keys.fromString(atKeyRaw);
        Secondary.Response llookupMetaRaw = executeCommand("llookup:meta:" + atKeyRaw, false);

        // 3
        atKey.metadata = Metadata.squash(atKey.metadata, Metadata.fromString(llookupMetaRaw.data)); // atKey.metadata has priority over llookupMetaRaw.data
        atKeys.add(atKey);
    }
    return atKeys;
}
```

1. Scan response is converted to a `String[]` via a util method in `StringUtil.java`
2. AtKey object is instantiated from `Keys.fromString(String)` which receives a String argument like `@bob:phone@alice`. `Keys.fromString(String)` uses `KeyStringUtil.java` to extract details from the fullKeyName.
3. The metadata of `atKey` is squashed with the metadata from a llookup verb command: `llookup:meta:<keyName>`, where the metadata originally within atKey has priority over the incoming metadata that is being fetched from the remote secondary server. `Metadata.fromString(String)` takes the `llookup:meta:<keyName>` verb response and returns a Metadata object where details were extracted.

### 2. Scan CLI
Scan CLI strictly uses `AtClient.getAtKeys(String)` like discussed.

As you can see below, the meta data is fetched from both the object itself and from the secondary.
(Example: `isEncrypted` came from the AtKey object during instantiation, and `ttl` came from the llookup to the secondary)
```
C:\Users\madiv\Desktop\GitHub\at_java> cmd /C ""C:\Program Files\OpenJDK\openjdk-11.0.13_8\bin\java.exe" @C:\Users\madiv\AppData\Local\Temp\cp_b3yf38okkfdcxflryrhfm2zes.argfile org.atsign.client.cli.Scan root.atsign.wtf:64 @sportsunconscious false ."
Found address of atSign "@sportsunconscious": ddbe1816-f40f-5b9f-bb2a-ba1492b93aec.staging0001.atsign.zone:3198

Enter index you want to llookup (l to list, q to quit):
l
atKeys: {
  0:  @farinataanxious:lemon@sportsunconscious
  1:  @farinataanxious:shared_key@sportsunconscious
  2:  @farinataanxious:test@sportsunconscious
  3:  @sportsunconscious:shared_key@sportsunconscious        
  4:  @sportsunconscious:signing_privatekey@sportsunconscious
  5:  public:publickey@farinataanxious
  6:  public:publickey@sportsunconscious
  7:  public:signing_publickey@sportsunconscious
  8:  shared_key.farinataanxious@sportsunconscious
  9:  shared_key.sportsunconscious@sportsunconscious
}

Enter index you want to llookup (l to list, q to quit):
9 
======================
Full KeyName: shared_key.sportsunconscious@sportsunconscious
KeyName: shared_key.sportsunconscious
Namespace: null
SharedBy: @sportsunconscious
SharedWith: null
KeyType: SelfKey
Metadata -------------------
ttl: 0
ttb: 0
ttr: null
ccd: null
dataSignature: null
sharedKeyStatus: null
isPublic: false
isEncrypted: true
isHidden: false
namespaceAware: true
isBinary: false
isCached: false
sharedKeyEnc: null
pubKeyCS: null
======================


Enter index you want to llookup (l to list, q to quit):
q

C:\Users\madiv\Desktop\GitHub\at_java>
```

Requirements:
- have keys for atSign in `keys/` for pkam authing
- script args: `<rootUrl> <atSign> <verbose == true|false> <scan regex>`

2022-07-09 13:17 UTC, JeremyTubongbanua commented
# 1. _getAtKeys
```java
private List<AtKey> _getAtKeys(String regex) throws AtException, ParseException {
    Response scanRawResponse = executeCommand("scan " + regex, false);
    ResponseTransformers.ScanResponseTransformer scanResponseTransformer = new ResponseTransformers.ScanResponseTransformer();
    List<String> rawArray = scanResponseTransformer.transform(scanRawResponse);
    List<AtKey> atKeys = new ArrayList<AtKey>(); 
    for(String atKeyRaw : rawArray) { // eg atKeyRaw == @bob:phone@alice
        AtKey atKey = Keys.fromString(atKeyRaw);
        Secondary.Response llookupMetaRaw = executeCommand("llookup:meta:" + atKeyRaw, false);
        atKey.metadata = Metadata.squash(atKey.metadata, Metadata.fromString(llookupMetaRaw)); // atKey.metadata has priority over llookupMetaRaw.data
        atKeys.add(atKey);
    }
    return atKeys;
}
```

# 2. Scan CLI example
```
Found address of atSign "@sportsunconscious": ddbe1816-f40f-5b9f-bb2a-ba1492b93aec.staging0001.atsign.zone:3198

Enter index you want to llookup (l to list, q to quit):
l
atKeys: {
  0:  @farinataanxious:lemon@sportsunconscious
  1:  @farinataanxious:shared_key@sportsunconscious
  2:  @farinataanxious:test@sportsunconscious
  3:  @sportsunconscious:shared_key@sportsunconscious        
  4:  @sportsunconscious:signing_privatekey@sportsunconscious
  5:  public:publickey@farinataanxious
  6:  public:publickey@sportsunconscious
  7:  public:signing_publickey@sportsunconscious
  8:  shared_key.farinataanxious@sportsunconscious
  9:  shared_key.sportsunconscious@sportsunconscious
}

Enter index you want to llookup (l to list, q to quit):      
0
======================
Full KeyName: @farinataanxious:lemon@sportsunconscious
KeyName: lemon
Namespace: null
SharedBy: @sportsunconscious
SharedWith: @farinataanxious
KeyType: SharedKey
Metadata -------------------
ttl: 0
ttb: 0
ttr: 5000
ccd: true
availableAt: 2022-06-19T20:35:09.962Z
expiresAt: null
refreshAt: 2022-06-19T21:58:29.962Z
createdAt: 2022-06-19T20:35:09.962Z
updatedAt: 2022-06-19T20:35:09.962Z
dataSignature: null
sharedKeyStatus: null
isPublic: false
isEncrypted: true
isHidden: false
namespaceAware: true
isBinary: false
isCached: false
sharedKeyEnc: null
pubKeyCS: null
======================


Enter index you want to llookup (l to list, q to quit):
q

C:\Users\madiv\Desktop\GitHub\at_java>
```

2022-07-09 20:19 UTC, JeremyTubongbanua commented
@gkc

If you believe this PR is ready, I can move onto the next thing.

2022-07-10 19:24 UTC, gkc approved these changes
Nice work Jeremy, thank you!

2022-07-10 19:26 UTC, gkc commented
> If you believe this PR is ready, I can move onto the next thing.

@JeremyTubongbanua Yes, thank you Jeremy, well done! I'll take care of merging to trunk this later this week as I need to merge some automated tests to trunk first, but yes, your work here is done

2022-07-18 22:15 UTC, merged

2022-07-20 19:51 UTC, JeremyTubongbanua commented
Some things I'm realizing this PR is missing:
1. namespace recognition in `KeyStringUtil.java` (as of right now, namespace is always null, but does not affect getting/deleting/updating the key in the secondary through the various AtClient implementations)
2. Scan CLI is missing "showHiddenKeys" argument