Added Conversion_Files.java
atsign-foundation/at_java pull request #60
Opened 2022-10-05 09:06 UTC by VinaySheth

**- What I did**
I have created a Java class which has 2 utility methods. This Java class can be used for effectively sending end-to-end encrypted files.

**- How I did it**
The first utility method converts a File object into an array of bytes (byte[]). The other method converts the byte[] back to a File object.

**- How to verify it**
The code can be verified as a 2 step process:
a. Firstly, you need to provide the name of the file you want to convert to array of bytes. The conversion of the specified file object to byte array will be done by the method 'fileToByteArray()'.
b. The byte array generated by the method 'fileToByteArray()' would be used by another method 'byteArrayToFile()' to reconstruct the file. This file would be saved as the Output (with same extension as that of the input).
The contents of both the input and output file will match proving that the inter-conversion is error free.

**- Description for the changelog**
Java file added to "at_client/src/main/java/org/atsign/client/util/Conversion_Files.java"

2022-10-05 09:34 UTC, VinaySheth commented
Added Conversion_Images.java

- What I did
I have created a Java class which has 2 utility methods. This Java class can be used for sending image files peer-to-peer. It ensures that the image file sent is only readable by the end user.

- How I did it
The first utility method converts an Image File object into an array of bytes (byte[]). The other method converts the byte[] back to an Image File object.

- How to verify it
The code can be verified as a 2 step process:
a. Firstly, you need to provide the name of the image file you want to convert to array of bytes. The conversion of the specified image file object to byte array will be done by the method 'imageToByteArray()'.
b. The byte array generated by the method 'imageToByteArray()' would be used by another method 'byteArrayToImage()' to reconstruct the image file. This image file would be saved as Output.jpg.
Both the image files will match, proving that the inter-conversion is error free.

- Description for the changelog
Java file added to "at_client/src/main/java/org/atsign/client/util/Conversion_Images.java"

2022-10-05 11:31 UTC, VinaySheth commented
@JeremyTubongbanua Please review this and let me know if any improvement is required. This fixes #53 and #54!

2022-10-05 11:34 UTC, VinaySheth commented
> Added Conversion_Images.java
> 
> * What I did
>   I have created a Java class which has 2 utility methods. This Java class can be used for sending image files peer-to-peer. It ensures that the image file sent is only readable by the end user.
> * How I did it
>   The first utility method converts an Image File object into an array of bytes (byte[]). The other method converts the byte[] back to an Image File object.
> * How to verify it
>   The code can be verified as a 2 step process:
>   a. Firstly, you need to provide the name of the image file you want to convert to array of bytes. The conversion of the specified image file object to byte array will be done by the method 'imageToByteArray()'.
>   b. The byte array generated by the method 'imageToByteArray()' would be used by another method 'byteArrayToImage()' to reconstruct the image file. This image file would be saved as Output.jpg.
>   Both the image files will match, proving that the inter-conversion is error free.
> * Description for the changelog
>   Java file added to "at_client/src/main/java/org/atsign/client/util/Conversion_Images.java"

@JeremyTubongbanua Please review this and let me know if any improvement is required. This fixes #53 and #54!

2022-10-14 14:16 UTC, JeremyTubongbanua requested changes

2022-10-14 14:16 UTC, JeremyTubongbanua commented on at_client/src/main/java/org/atsign/client/util/Conversion_Images.java
> +	public static File byteArrayToImage(byte data[])throws IOException
Please have this return the BufferedImage object

2022-10-14 14:43 UTC, JeremyTubongbanua requested changes
Sorry one last thing-

Could you please have this method receive a `File` object instead of the `String filename`?

2022-10-14 14:44 UTC, JeremyTubongbanua requested changes
Thanks @VinaySheth :)

See requested changes, please.

2022-10-14 14:44 UTC, JeremyTubongbanua commented on at_client/src/main/java/org/atsign/client/util/Conversion_Files.java
> +	public static byte[] fileToByteArray(String filename)throws IOException
This should be `byte[] fileToByteArray(File file);`

2022-10-14 14:44 UTC, JeremyTubongbanua commented on at_client/src/main/java/org/atsign/client/util/Conversion_Images.java
> +	public static byte[] imageToByteArray(String filename)throws IOException
same thing here, this should receive `File file` instead of `String filename`

2022-10-14 14:56 UTC, VinaySheth commented on at_client/src/main/java/org/atsign/client/util/Conversion_Images.java
> +	public static byte[] imageToByteArray(String filename)throws IOException
I have made the necessary changes. Please check it @JeremyTubongbanua.

2022-10-14 17:13 UTC, JeremyTubongbanua approved these changes
Thank you @VinaySheth :)

2022-10-14 17:17 UTC, merged

2022-10-25 17:20 UTC, JeremyTubongbanua commented
@VinaySheth 
Hey! Thank you for your contribution. Your PR was accepted, merged, and it closed an issue. You could be eligible for a prize. 

To be eligible, please send an email to [hacktoberfest@atsign.com](mailto:hacktoberfest@atsign.com) with a screenshot of the PR approval email. This is to prove that your email corresponds to the correct GitHub account. Thank you!