feat: String <-> byte[]
atsign-foundation/at_java pull request #62
Opened 2022-10-11 15:43 UTC by sid172014

Closes #61 issue

**- What I did** -> i made a new class i.e "ByteUtil.java" to convert a string to byte array and vice versa

**- How I did it** -> I used the inbuilt 'new String()' function to convert the byte array data to string and the inbuilt '.getBytes()' to get bytes from a given string

**- How to verify it**-> Pass in String value as a parameter in 'convert()' function to verify string to byte[] array and a byte[] array as a parameter in 'convert()' function to verify the byte[] array to string conversion

**- Description for the changelog**

2022-10-11 16:21 UTC, JeremyTubongbanua commented
Hey @sid172014 thanks for doing this
Could you also write some tests under `test/java/org/atsign/common/` -sorry I forgot to put that in the ticket.

2022-10-11 16:22 UTC, JeremyTubongbanua requested changes
Hey @sid172014 thanks for doing this
Could you also write some tests under `test/java/org/atsign/common/` -sorry I forgot to put that in the ticket.

2022-10-11 16:35 UTC, sid172014 commented
@JeremyTubongbanua can i just comment their inputs and outputs inside the test files with the main code coz i looked over other tests files and i dont think im familiar with 'assertions'

2022-10-12 18:56 UTC, JeremyTubongbanua commented
> @JeremyTubongbanua can i just comment their inputs and outputs inside the test files with the main code coz i looked over other tests files and i dont think im familiar with 'assertions'

Hey @sid172014, that's okay, it's quite simple. Take a look at the `DateUtilTest.java` file: https://github.com/atsign-foundation/at_java/blob/trunk/at_client/src/test/java/org/atsign/common/DateUtilTest.java

You just "assert" that something is true. In the off chance that it is not true (and the test case fails) then we will know that the code is not working as intended.

Get your hands dirty with this and don't be afraid to make mistakes =) Writing tests isn't as bad as it seems. We have a [discord](https://discord.atsign.com) where I will be able to reply faster if you need help.

2022-10-12 19:05 UTC, sid172014 commented
Sure ! imma learn that right away and thanks for the discord server

2022-10-25 03:19 UTC, JeremyTubongbanua commented
Hey @sid172014, any progress on this?

2022-10-25 09:41 UTC, sid172014 commented
Hey @JeremyTubongbanua im really really sorry for the delay , i literally had the codes written on the day we had our last conversation , but i forgot to make the PR , i did it now , please have a look

2022-10-25 16:29 UTC, JeremyTubongbanua requested changes
Please see suggested changes.

Also please revert the following files that you've committed:
- `.DS_Store`
- `.idea/`

We don't need your IDE files to be part of the repository (because everyone might have different project settings). 

After that, it LGTM. Thanks for your work :)

2022-10-25 16:29 UTC, JeremyTubongbanua commented on ByteUtil.java
> +
1. Please put `ByteUtil.java` under `at_client/src/main/java/org/atsign/client/util/`

2022-10-25 16:29 UTC, JeremyTubongbanua commented on ByteUtil.java
> +    public String convert(byte[] data){ // Method to convert byte[] array to string
Make this a static method so you don't have to create an object to use it. Ideally, you would be able to use it like this:
`String s = ByteUtil.convert(data);`

2022-10-25 16:29 UTC, JeremyTubongbanua commented on ByteUtil.java
> +    public byte[] convert(String data){ // Method to convert String to byte[] array
Same thing here, make this a static method.

2022-10-25 16:31 UTC, JeremyTubongbanua requested changes
After you change them to static methods, please edit your tests.

2022-10-25 16:31 UTC, JeremyTubongbanua commented on at_client/src/test/java/org/atsign/common/ByteUtilTest.java
> +        ByteUtil byteUtil = new ByteUtil();
Once you've made them into static methods, you can get rid of this line because you don't need to create an object to use the class.

2022-10-25 16:31 UTC, JeremyTubongbanua commented on at_client/src/test/java/org/atsign/common/ByteUtilTest.java
> +        assertEquals("JeremyTubongbanua ",byteUtil.convert(bytec));
Then `byteUtil.convert(bytec)` would become `ByteUtil.convert(bytec)`

2022-10-25 16:32 UTC, JeremyTubongbanua commented
You're doing great @sid172014! After those changes, it will be good to merge.

2022-10-25 16:48 UTC, sid172014 commented
Hey @JeremyTubongbanua , i did the changes you asked for , can you please check ...

2022-10-25 19:11 UTC, JeremyTubongbanua approved these changes

2022-10-25 19:12 UTC, JeremyTubongbanua commented
@sid172014 
Hey! Thank you for your contribution. Your PR was accepted, merged, and it closed an issue. You could be eligible for a prize. 

To be eligible, please send an email to [hacktoberfest@atsign.com](mailto:hacktoberfest@atsign.com) with a screenshot of the PR approval email. This is to prove that your email corresponds to the correct GitHub account. Thank you!

When it comes time to distribute the prizes, we will look at all the emails we've received from that email so don't forget to do this!

2022-10-25 19:15 UTC, JeremyTubongbanua requested changes

2022-10-25 19:15 UTC, JeremyTubongbanua commented on at_client/src/test/java/org/atsign/common/ByteUtilTest.java
> +
Tests are failing. I think it is because you did not import `ByteUtil`

2022-10-26 05:57 UTC, sid172014 commented
Hey @JeremyTubongbanua ive made the changes , Sorry for that silly mistake

2022-10-26 13:59 UTC, closed without merging